### ISSUE TITLE
[EZ-GANTT] Set Up GitHub Actions for Tests and Dynamic Badges 🛠

### ISSUE THREAD

**Issue by paul0lden** [paul0lden/ez-gantt#18]
#### **Overview**
This task involves setting up **GitHub Actions** to automate testing and CI/CD workflows, along with integrating **dynamic badges** into the repository’s **README.md**. The badges will display important information such as test status, code coverage, build passing status, npm downloads, and the latest published version.

---

#### 1. **Set Up GitHub Actions for Running Tests**:
   - **Purpose**: Automate testing using **GitHub Actions** whenever there’s a new pull request or push to the main branch.
   - **Content**:
     - Create a new **GitHub Actions workflow** file (e.g., `.github/workflows/test.yml`) to run tests automatically.
     - Use a **matrix** strategy to test across multiple Node.js versions (e.g., Node.js `16`, `18`).
     - Ensure tests run for all branches and pull requests.

   **Acceptance Criteria**:
   - [ ] GitHub Actions workflow is set up to run tests on every push and pull request.
   - [ ] Tests run across multiple Node.js versions (e.g., `16`, `18`).
   - [ ] The workflow reports test results and shows status (passing or failing).

#### Example **GitHub Actions** Workflow (`test.yml`):
```yaml
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]  # Test on multiple Node.js versions
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
```

---

#### 2. **Set Up Test Coverage with a Badge**:
   - **Purpose**: Track and display **test coverage** using a tool like **Codecov** or **Coveralls** and display it as a badge in the README.
   - **Content**:
     - Integrate **Codecov** or **Coveralls** into the GitHub Actions workflow to upload test coverage reports after tests run.
     - Add a dynamic **test coverage badge** to the README to show the percentage of test coverage.

   **Acceptance Criteria**:
   - [ ] Test coverage is tracked with **Codecov** or **Coveralls** and included in the GitHub Actions workflow.
   - [ ] A dynamic **test coverage badge** is added to the README.

#### Example **Codecov Integration**:
```yaml
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Set the token in GitHub secrets
```

- **Badge to Add to README**:
```md
![Test Coverage](https://codecov.io/gh/username/repo/branch/main/graph/badge.svg)
```

---

#### 3. **Add a Passing Status Badge**:
   - **Purpose**: Display a **passing status badge** in the README to show whether the latest GitHub Actions tests/builds are passing.
   - **Content**:
     - Add a GitHub Actions badge to show the build/test passing status dynamically.

   **Acceptance Criteria**:
   - [ ] The README includes a **passing status badge** from the GitHub Actions pipeline.

#### **Badge to Add to README**:
```md
![Build Status](https://github.com/username/repo/actions/workflows/test.yml/badge.svg)
```

---

#### 4. **Add Dynamic NPM Badges**:
   - **Purpose**: Display **npm-related badges** (e.g., **downloads**, **latest version**) in the README for quick reference.
   - **Content**:
     - Add a badge for **npm downloads** to track the popularity of the package.
     - Add a badge for the **latest version** of the package to easily show users which version is currently published.

   **Acceptance Criteria**:
   - [ ] README includes an **npm downloads** badge.
   - [ ] README includes a **latest version** badge.

#### **Badges to Add to README**:
```md
![npm](https://img.shields.io/npm/v/your-package-name)
![npm](https://img.shields.io/npm/dm/your-package-name)
```

---

#### 5. **Add Last Commit and License Badges**:
   - **Purpose**: Display additional information like the **last commit date** and the **license** of the repository in the README.
   - **Content**:
     - Add a badge for the **last commit** to show when the repository was last updated.
     - Add a badge for the repository **license** for transparency.

   **Acceptance Criteria**:
   - [ ] README includes a **last commit** badge.
   - [ ] README includes a **license** badge.

#### **Badges to Add to README**:
```md
![GitHub last commit](https://img.shields.io/github/last-commit/username/repo)
![GitHub](https://img.shields.io/github/license/username/repo)
```

---

### **Acceptance Criteria Summary**:
- [ ] GitHub Actions are set up to automatically run **tests** on every push and pull request.
- [ ] Test coverage is tracked using **Codecov** or **Coveralls**, and a **coverage badge** is added to the README.
- [ ] A **passing status badge** from GitHub Actions is added to the README.
- [ ] Dynamic **npm badges** (downloads and latest version) are added to the README.
- [ ] A **last commit badge** is added to the README.
- [ ] A **license badge** is included in the README.

---

### **Resources**:
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Codecov GitHub Action](https://github.com/codecov/codecov-action)
- [Shields.io for Badges](https://shields.io/)
